export const productos = [
    {id: 1, image: '/imagenes/cuidadoPersonal-shampooLorealParis.png', title: 'LOREAL PARIS', description:'Shampoo Elvive Oleo Extraordinario', price: 423, category: 'cuidadoPersonal'},
    {id: 2, image: '/imagenes/cuidadoPersonal-acondicionadorLorealParis.png', title: 'LOREAL PARIS', description:'Acondicionador Elvive Oleo Extraordinario', price: 423, category: 'cuidadoPersonal'},
    {id: 3, image: '/imagenes/cuidadoPersonal-aguaMicelarGarnier.png', title: 'GARNIER', description:'Agua Micelar Garnier Skin Active', price: 1000, category: 'cuidadoPersonal'},
    {id: 4, image: '/imagenes/cuidadoPersonal-cepilloDentalColgate.png', title: 'COLGATE', description:'Cepillo Dental Colgate', price: 500, category: 'cuidadoPersonal'},
    {id: 5, image: '/imagenes/cuidadoPersonal-cepilloDentalOralB.png', title: 'ORAL-B', description:'Cepillo Dental Oral-B', price: 500, category: 'cuidadoPersonal'},
    {id: 6, image: '/imagenes/cuidadoPersonal-papelHigienicoHigienol.png', title: 'HIGIENOL', description:'Papel Higiénico Higienol', price: 500, category: 'cuidadoPersonal'},
    {id: 7, image: '/imagenes/cuidadoPersonal-toallitasFemeninasKotex.png', title: 'KOTEX', description:'Toallitas Femeninas Kotex', price: 500, category: 'cuidadoPersonal'},
    {id: 8, image: '/imagenes/cuidadoPersonal-cremaDentalColgate.png', title: 'COLGATE', description:'Crema Dental Colgate', price: 500, category: 'cuidadoPersonal'},
    {id: 9, image: '/imagenes/cuidadoPersonal-enjuagueBucalColgate.png', title: 'COLGATE', description:'Enguaje Bucal Colgate', price: 500, category: 'cuidadoPersonal'},
    {id: 10, image: '/imagenes/cuidadoPersonal-acondicionadorLorealParis1.png', title: 'LOREAL PARIS', description:'Acondicionador Elvive Oleo Extraordinario', price: 500, category: 'cuidadoPersonal'},
    {id: 11, image: '/imagenes/cuidadoPersonal-jabonEnBarraDove.png', title: 'DOVE', description:'Jabón en Barra Dove', price: 500, category: 'cuidadoPersonal'},
    {id: 12, image: '/imagenes/cuidadoPersonal-mascaraGarnierFructis.png', title: 'GARNIER', description:'Máscara Garnier Fructis', price: 500, category: 'cuidadoPersonal'},
    {id: 13, image: '/imagenes/limpieza-esponjaVirulana.png', title: 'VIRULANA', description:'Esponja Virulana Multiuso', price: 150, category: 'limpieza'},
    {id: 14, image: '/imagenes/limpieza-limpiadorCif.png', title: 'CIF', description:'Limpiador Cif Ultra Blanco en Gel', price: 445, category: 'limpieza'},
    {id: 15, image: '/imagenes/limpieza-jabonLiquidoSkip.png', title: 'SKIP', description:'Jabón Líquido para diluir Skip', price: 1030, category: 'limpieza'},
    {id: 16, image: '/imagenes/limpieza-pañosVileda.png', title: 'VILEDA', description:'Paños Microfibra Vileda Multiuso', price: 1579, category: 'limpieza'},
    {id: 17, image: '/imagenes/limpieza-suavizanteQuerubin.png', title: 'QUERUBIN', description:'Suavizante para ropa Querubín', price: 500, category: 'limpieza'},
    {id: 18, image: '/imagenes/limpieza-limpiadorMultisuperficiesCif.png', title: 'CIF', description:'Limpiador Multisuperficies Cif', price: 500, category: 'limpieza'},
    {id: 19, image: '/imagenes/bebes-lecheEnPolvoNutrilon.png', title: 'NUTRILON', description:'Leche de fórmula en polvo sin TACC Nutricia Bagó Nutrilon Profutura', price: 3667, category: 'bebes'},
    {id: 20, image: '/imagenes/bebes-oleoCalcareoEstrella.png', title: 'ESTRELLA BABY', description:'Oléo Calcáreo Estrella Baby sin fragancia', price: 1135, category: 'bebes'},
    {id: 21, image: '/imagenes/bebes-pañalesPampers.png', title: 'PAMPERS', description:'Pañales Pampers Premium Care', price: 3424, category: 'bebes'},
    {id: 22, image: '/imagenes/bebes-toallitasHumedasHuggies.png', title: 'HUGGIES', description:'Toallitas Húmedas Huggies', price: 560, category: 'bebes'},
]